### ISSUE TITLE
Crashing in Release-mode

### ISSUE THREAD

**Issue by Frexuz** [markuswind/react-native-select-input-ios#10]
I could just import this, without even using it.. and the app would crash right after the default RN splash screen
```
import SelectInput from 'react-native-select-input-ios'
```

Eventually I got the iOS crash report. It doesn't say much (to me), and I had to remove every import one by one to eventually getting it to run by removing SelectInput.

![screen shot 2017-10-30 at 20 27 54](https://user-images.githubusercontent.com/49692/32176706-66975d08-bdc3-11e7-8938-dd638320ca55.png)

It's running fine in Debug-mode.

Edit: Another report from a different reporting tool:

```
RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating ‘p.View.propTypes.style’): Unhandled JS Exception: undefined is not an object (evaluating ’p.View.prop..., stack: <unknown>@1474:1897 i@2:553 <unknown>@1473:79 i@2:553 <unknown>@1472:203 i@2:553 <unknown>@867:662 i@2:553 <unknown>@13:430 i@2:553 <unknown>@12:30 i@2:553 n@2:266 glob
```

Just taking a wild guess here: Seems like `View.propTypes.style` is deprecated. Maybe use [StyleSheetPropsTypes](https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheetPropType.js) instead?

**Comment by markuswind** [comment]
This is happening since RN0.49? I'll update the example project and see if I can fix this soon!

**Comment by Frexuz** [comment]
Yes, since 0.49 :) Thanks!

**Comment by pedroslopez** [comment]
Yeah, I recently updated to Exp v22 / RN v0.49. The app crashes in production mode because of the use of View.propTypes.style (it's been deprecated in favor of ViewPropTypes)

Would appreciate the fix, thanks in advance! :)

**Comment by pedroslopez** [comment]
I found the fix to be quite simple and quick, so decided to implement it myself. PR #11
