### ISSUE TITLE
someone can you help me? i need to open a screen page on press of the date picker text options

### ISSUE THREAD

**Issue by pherm** [markuswind/react-native-select-input-ios#13]

**Comment by markuswind** [comment]
I'm not sure what you mean by this. But can't you do such things on the onPress event?

**Comment by pherm** [comment]
i try this code in SelectInput:`onPress={() => navigation.navigate("screen2")}` and `onSubmitEditing={() => navigation.navigate("screen5")}`

anyway never work.
