### ISSUE TITLE
'fontFamily' is not recognized by labelStyle

### ISSUE THREAD

**Issue by gitsad** [markuswind/react-native-select-input-ios#17]
labelStyle prop works fine on iOS but on Android it has problem showed below:
![screen shot 2018-03-07 at 11 25 06](https://user-images.githubusercontent.com/13887724/37087386-67d9fdba-21fa-11e8-8939-40b5e49b19fe.png)

It doesn't recognize fontFamily nor textAlign.

**Comment by markuswind** [comment]
Sorry for the late response, do you have any idea how to fix this? It's probably something small?
