### ISSUE TITLE
是否应该抛出一个方法拿到对应选择value

### ISSUE THREAD

**Issue by YNameUndefined** [markuswind/react-native-select-input-ios#34]
组件的value值是根据索引匹配label，不能直接拿到label。导致使用该组件我需要写多余的匹配规则？

**Comment by markuswind** [comment]
**google translate**

The value of the component is based on the index matching label, can not get the label directly. I need to write extra matching rules to use this component?

**Comment by markuswind** [comment]
I'm not sure if the translation is correct. But if it, than the answer is yes.
