### ISSUE TITLE
Pass through picker onValueChange

### ISSUE THREAD

**Issue by jdegger** [markuswind/react-native-select-input-ios#39]
When the picker value changes, we want some event to update the view immediately with the selected value. Instead of having the user click done.

We managed to change the lower level API by adding this to the onSubmitEditing function:

```javacript
// waiting one tick to have all the context available
setTimeout(() => {

  // hijack function
  this.picker.pickerKeyboard.onValueChange = (value) => {

    // pass to own class
    this.onValueChange(value);

    // normal function
    this.picker.pickerKeyboard.setState({
      value: value,
    });

  };

}, 0);
```
This is not ideal but it works. Exposing the onValueChange would be a great addition.

Thanks for the work on this plugin, highly appreciated!

**Comment by markuswind** [comment]
So it would look like this https://github.com/markuswind/react-native-select-input-ios/pull/35/commits/aa1d89ac406049a13b3fd04a57ae9d492d8a89d8? Or do you think it should also be triggered on `onSubmit` on Android?

I haven't been working on `v2.0` for a while, but I might be picking it up again soon!

**Comment by jdegger** [comment]
That looks great 👍  I'm not sure about Android, we have been solely implementing on iOS. However, I can take a look at the Android behavior tomorrow if you want?

aa1d89a is great tho, highly appreciated!

**Comment by jdegger** [comment]
You seem to have scoped this for v2, no problem at all since we have a working version. When do you expect this version to be released? Do you need any help?

Cheers to the quick responses.
