### ISSUE TITLE
iPhone 6+ & 7+ shows large transparent borders around keyboard buttons

### ISSUE THREAD

**Issue by jkingworking** [markuswind/react-native-select-input-ios#4]
On iOS devices with high pixel density (iPhone 6+ & 7+) the borderTopWidth of 0.5 on the buttonview is causing large transparent borders around keyboard buttons.

It's caused by this underlying issue https://github.com/facebook/react-native/issues/12401

I put in a pull request that addresses. #3

**Comment by markuswind** [comment]
Thanks, merged.
