### ISSUE TITLE
Warning: Label Style does not accept color style

### ISSUE THREAD

**Issue by grantbi** [markuswind/react-native-select-input-ios#42]
Warning: Failed prop type: Invalid props.labelStyle key `color` supplied to `SelectInput`.
Bad object: {
  "backgroundColor": "#ffffff",
  "padding": 10,
  "marginLeft": 10,
  "marginVertical": 5,
  "flex": 1,
  "color": "#666666"
}
Valid keys: 
Looks like it doesn't accept TextInputStyle as a prop-type?

**Comment by ramon90** [comment]
yes there is a bug

**Comment by rafaelsts** [comment]
I got this error to, any way to fix it?

**Comment by pansinyoung** [comment]
Having the same issue, using text prop types for labelStyle and getting the warning. The style actually works but it might be better if the warning can be removed.
The solution might be making labelStyle prop types one of TextPropTypes and ViewPropType?

**Comment by danial031193** [comment]
Same problem with buttonsTextStyle propTypes on ios. style: { fontSize: 18 } gives an error message

**Comment by markuswind** [comment]
Please let me know if these issues are fixed in `v2.0.2`.

**Comment by danial031193** [comment]
> Please let me know if these issues are fixed in `v2.0.2`.

Thank you, it works
