### ISSUE TITLE
Select Mode Stick to Dropdown

### ISSUE THREAD

**Issue by paulolops** [markuswind/react-native-select-input-ios#45]
Hello !
I've encountered a problem with the mode of my select, whatever the mode I choose : 'dialog' or 'dropdown' it seems to work as a dropdown.
Also I am running this component on android.

**Comment by InfoAjay** [comment]
I'm also having the same problem...
please let me know if you get the solution.

**Comment by paulolops** [comment]
Still no solution found to this day, authors don't seem to care much either ...

**Comment by markuswind** [comment]
Hello! Sadly I can't reproduce this with the example project. Could you please specify which versions of `react-native` and `react-native-select-input-ios` you are using? 

I don't think they have changed anything related to this in the `Picker` component, so I currently don't have a clue on why this is happening.

**Comment by paulolops** [comment]
Hello, 
I currently use react-native v0.59.4 and react-native-select-input-ios v2.0.1

And to explain the problem a little more :
It seems that whatever value I give to the "mode" option for the SelectInput ('dialog', 'dropdown' or none) of my app, the render stays a dropdown one.

**Comment by InfoAjay** [comment]
I'm using **"react-native": "0.59.5"** and **"react-native-numeric-input": "^1.6.5"**

**Comment by didac-wh** [comment]
@paulolops @InfoAjay The problem goes beyond the scope of this package. Actually is somehow beyond the scope of the react native team :)
https://github.com/facebook/react-native/issues/24055

**Comment by paulolops** [comment]
Thanks for your help @didac-wh,
I hope they will fix this issue quite fast, sorry for the bother and have a nice day all !
