### ISSUE TITLE
the onValueChange not working in android

### ISSUE THREAD

**Issue by enieber** [markuswind/react-native-select-input-ios#52]
I use the lib but the `onValueChange` not working in android, only `onSubmitEditing` .

version lib: 2.0.2
react-native version: 0.59.9

**Comment by markuswind** [comment]
Yeah, it could be changed to make it trigger `onValueChange` as well. But there's a reason for not triggering the `onValueChange` on Android. It's because you can't scroll through the values like you can do on the `iOS` picker.

**Comment by puremana** [comment]
Really not sure why this issue was closed, I had also expected it to be triggered when I had changed a value
