### ISSUE TITLE
componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by puremana** [markuswind/react-native-select-input-ios#56]
Hi, thank you for your work on this amazing package.
However I'm constantly getting warnings regarding <SelectInput> and componentWillReceieveProps.

```
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: SelectInput

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

Currently testing with Android.

Looks componentWillReceieveProps is used in `AbstractSelectInput.js`, `PickerKeyboard.spec.js` and `PickerKeyboard.js`.

Thanks

**Comment by dehlen** [comment]
any update on this? We also see this warning and really do not want to maintain a fork just because of this warning.

**Comment by dehlen** [comment]
Thank you for resolving the issue 👍
