### ISSUE TITLE
Value not being set on android

### ISSUE THREAD

**Issue by pedroslopez** [markuswind/react-native-select-input-ios#6]
Hi, we're having a small problem using this component on Android.

We're using redux and have a property that's being mapped. This property is the one that's being used to set the select input's "value" prop but while it works fine on iOS (the value updates whenever the property is updated), this is not the case on android.

Setting a default value manually to a constant works. The problem arises when we're using a prop to set the default value.

Checking the prop inside the render function right before passing it to the Select input, it has the correct value.

Thanks for your help in advance

**Comment by markuswind** [comment]
Ah, I think I might see what's causing this. I'll try to fix this soon!

**Comment by markuswind** [comment]
Could you check if the issue is fixed in v1.1.1?

**Comment by KirillPd** [comment]
Hey @markuswind. I don't know is it connected with this issue. So, the issue is that `onSubmitEditing` callback sometimes doesn't fire. It works perfect on Android but on iOS I face this bug on every 3-4 `Done` click.

I'm using v1.1.1.

**Comment by pedroslopez** [comment]
Yep, it works fine now. Thanks!
