### ISSUE TITLE
iOS. `onSubmitEditing` callback doesn't fire sometimes

### ISSUE THREAD

**Issue by KirillPd** [markuswind/react-native-select-input-ios#8]
Hey @markuswind. So, the issue is that `onSubmitEditing` callback sometimes doesn't fire. It works perfect on Android but on iOS I face this bug on every 3-4 `Done` click.

I'm using v1.1.1.

**Comment by markuswind** [comment]
Hey, I think that's because it's not done scrolling? The Picker inside the PickerKeyboard won't fire onValueChange unless it stopped scrolling.

This is standard behaviour in http://facebook.github.io/react-native/releases/0.49/docs/picker.html#picker

**Comment by KirillPd** [comment]
It happens even when I click the `Done` button immediately without scrolling.

**Comment by KirillPd** [comment]
Also, I noticed that it works as expected if I wait 2-3 second after modal opening. Hmmm... Maybe it is the native `Picker` component problem. So I'll close this issue for now. Thanks!

**Comment by KirillPd** [comment]
Unfortunately I have faced this issue many times. Fixed it by adding `this._value` variable in `PickerKeyboard` constructor outside the state object. Like this:

```
class PickerKeyboard extends Component {
  constructor(props) {
    super(props);

    // refs
    this.customKeyboard = null;

    // initial state
    this.state = {
      value: props.value,
      visible: false,
    };

    this._value = null; // <- HERE
  }

...

```
And then i passed this `_value` variable into `onSubmitPress` instead of `this.state.value`:

```
onSubmitPress() {
    this.setVisible(false);

    let onSubmit = this.props.onSubmit;
    onSubmit && onSubmit(this._value);
}
```

So, looks like sometimes state doesn't update when we click on `Done` button.

**Comment by markuswind** [comment]
Hmm ok, and how are you updating the this._value property?

**Comment by KirillPd** [comment]
```
  onValueChange(value) {
    this._value = value;
    ...
  }
```

I edited my previous comment. Looks like this attempt doesn't work too. Don't know what to do

**Comment by KirillPd** [comment]
Finally, I added this strings to the `PcikerKeyboard` component:

```
  shouldComponentUpdate(prevProps, prevState) {
    if (prevState.visible != this.state.visible) {
      if (this.picker) {
        this.onSubmitPress(this.picker.props.selectedValue);
      }
    }

    return true;
  }
```

And it works so far!

**Comment by markuswind** [comment]
Alright! I don't think I'll add this, seems like this will also trigger when you're not actually pressing the done button. Perhaps you're not handling the value correctly in your parent view?

I'll close this issue for now.

**Comment by KirillPd** [comment]
Yeap, for now it triggers on all close events too. But I'll fix it. 

> Perhaps you're not handling the value correctly in your parent view?

I'm just using this package. So the parent view is the `SelectInput.ios.js` component

**Comment by KirillPd** [comment]
In case if somebody meets this problem here is the link to my hack:
https://github.com/KirillPd/react-native-select-input-ios/blob/master/src/components/PickerKeyboard.js
